[package]
name = "btree-indexmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-btree = { path = "../generic-btree" }
slab = "*"
slab-lists = { path = "../slab-lists" }
smallvec = "*"